---
- name: Installing Golang
  apt: pkg={{ item }}
  with_items:
    - golang
    - golang-go.tools
    - mercurial
  sudo: yes
  tags:
    - golang

- name: Exporting Golang env variables
  lineinfile: dest=~/.zshrc state=present line={{ item }}
  with_items:
    - export GOPATH=$HOME/go
    - export PATH=$PATH:$GOPATH/bin
