---
- name: Installing Golang
  apt: pkg={{ item }}
  with_items:
    - golang
    - golang-go.tools
    - mercurial
  sudo: yes
  tags:
    - golang

- name: Creating workspace dir
  file: path=~/go state=directory
  sudo: no
  tags:
    - golang

- name: Exporting GOPATH
  lineinfile: dest=~/.zshrc state=present line="export GOPATH=$HOME/go"
  sudo: no
  tags:
    - golang

- name: Exporting PATH
  lineinfile: dest=~/.zshrc state=present line="export PATH=$PATH:$GOPATH/bin"
  sudo: no
  tags:
    - golang
