---
- name: Checking out My Vim
  git: repo=https://github.com/katcipis/my.vim.git dest=/tmp/my.vim

- name: Installing My Vim
  command: make install chdir=/tmp/my.vim

- name: Checking out My Fonts
  git: repo=https://github.com/katcipis/my.fonts.git dest=/tmp/my.fonts

- name: Installing My Fonts
  command: make install chdir=/tmp/my.fonts

- name: Checking out My ZSH
  git: repo=https://github.com/katcipis/my.zsh.git dest=/tmp/my.zsh

- name: Installing My ZSH
  command: make install chdir=/tmp/my.zsh
