---
- name: Checking out My Vim
  sudo: no
  git: repo=https://github.com/katcipis/my.vim.git dest=/tmp/my.vim

#- name: Installing My Vim
  #sudo: no
  #command: make install chdir=/tmp/my.vim

- name: Checking out My Fonts
  sudo: no
  git: repo=https://github.com/katcipis/my.fonts.git dest=/tmp/my.fonts

- name: Installing My Fonts
  sudo: no
  command: make install chdir=/tmp/my.fonts

- name: Checking out My ZSH
  sudo: no
  git: repo=https://github.com/katcipis/my.zsh.git dest=/tmp/my.zsh

- name: Installing My ZSH
  sudo: no
  command: make install chdir=/tmp/my.zsh
