---
- name: Install zsh
  apt: pkg=zsh state=latest

- name: Setting zsh as default shell
  command: chsh -s /bin/zsh vagrant

- name: Copying zshrc
  synchronize: src=~/.zshrc dest=/home/vagrant/.zshrc

- name: Copying zsh dir
  synchronize: src=~/.zsh dest=/home/vagrant/.zsh
