---

- name: Install stuff
  apt: pkg={{ item }}
  with_items:
    - ruby1.9.3
    - nodejs

- name: Getting blog
  git: repo=https://github.com/katcipis/katcipis.github.io.git dest=/home/vagrant/blog accept_hostkey=true
  sudo: no

- name: Checking out the source branch
  command: git checkout source chdir=/home/vagrant/blog

- name: Installing bundler
  command: gem install bundler chdir=/home/vagrant/blog

- name: Bundle install on the blog
  command: bundle install chdir=/home/vagrant/blog
  sudo: no
