---
- name: Install ctools
  apt: pkg={{ item }}
  with_items:
    - pkg-config
    - autogen
    - autoconf
    - autopoint
    - libtool
    - bison
    - flex
    - gtk-doc-tools
    - build-essential
  sudo: yes
  tags:
    - ctools
    - packages
