---
- name: Install stuff
  apt: pkg={{ item }}
  with_items:
    - pkg-config
    - autogen
    - autoconf
    - build-essential
    - vim
    - exuberant-ctags
  sudo: yes
  tags:
    - stuff
    - packages
