---
- name: Disable IPv6
  command: sysctl net.ipv6.conf.all.disable_ipv6=1
  sudo: yes
  tags:
    - common
    - ipv6

- name: Update apt cache and upgrade system
  apt: upgrade=dist update-cache=yes
  sudo: yes
  tags:
    - common
    - update
    - upgrade

- name: Install language-pack-en
  apt: pkg=language-pack-en
  sudo: yes
  tags:
    - common
    - packages
    - language

- name: Update locale to {{ locale }}
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
  sudo: yes
  tags:
    - common
    - language

- name: Update localtime to {{ timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime
  sudo: yes
  tags:
    - common
    - localtime

- name: Update timezone to {{ timezone }}
  template: src=default-timezone.j2 dest=/etc/timezone
  sudo: yes
  tags:
    - common
    - timezone

- name: Update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
  sudo: yes
  tags:
    - common
    - tzdata
