---
- name: Stopping and disabling puppet agent
  service: name=puppet state=stopped enabled=no
  sudo: yes
  tags:
    - puppet

- name: Disable puppetlabs repo
  replace: dest=/etc/apt/sources.list.d/puppetlabs.list regexp='^deb' replace='#deb' backup=no
  sudo: yes
  tags:
    - puppet
